name: test-prettier-eslint
on: [push]

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name : import proyect
  run-test:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install
      - run: npm run prettier
      - run: npm run eslint
      - name: run test prettier and eslint
